import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/shared/components//navbar/NavBar.component";
import { AuthProvider } from "@/modules/auth/shared/context/Auth.context"

import { ProductsProvider } from "../modules/user/pages/manager/context/Products.context";
import Chatbot from "@/shared/components/Chatbot";
import { CartProvider } from "@/modules/checkout/pages/cart/context/Cart.context";
import { CategoriesProvider } from "@/modules/user/pages/manager/context/Categories.context";
import Footer from "@/shared/components/Footer/FooterView";

export const metadata: Metadata = {
  title: "The Ink3d project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">

      <body>
        <CategoriesProvider>
          <ProductsProvider>
            <AuthProvider>
              <CartProvider>
                <NavBar />
                
                  <main className="bg-[#D9D9D9] flex-grow">
                    <Chatbot />
                    {children}
                  </main>
                
                
              </CartProvider>
            </AuthProvider>
          </ProductsProvider>
        </CategoriesProvider>

      </body>
    </html>
  );
}