import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/shared/components/navbar/NavBar.component";
import { AuthProvider } from "@/modules/auth/shared/context/Auth.context";
import { ProductsProvider } from "@/modules/user/pages/manager/context/Products.context";
import Chatbot from "@/shared/components/Chatbot";
import { CategoriesProvider } from "@/modules/user/pages/manager/context/Categories.context";
import Footer from "@/shared/components/footer/Footer";
import { CartProvider } from "@/modules/checkout/pages/cart/context/Cart.context";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className="flex flex-col min-h-screen">
        <ProductsProvider>
          <AuthProvider>
            <CartProvider>
              <CategoriesProvider>
                <Chatbot />
                <NavBar />
                <div className="flex flex-col flex-grow">
                  <main className="bg-[#D9D9D9] pt-20">{children}</main>
                </div>
              </CategoriesProvider>
            </CartProvider>
          </AuthProvider>
        </ProductsProvider>
        <Footer />
      </body>
    </html>
  );
}

